# -*- coding: utf-8 -*-
"""
Модуль для обработки игровых действий.

Этот файл содержит основной обработчик для всех игровых действий,
которые инициируются через отправку текстовых сообщений из инлайн-режима.

Module for handling game actions.

This file contains the main handler for all game actions initiated
by sending text messages from the inline mode.
"""

from aiogram import F, Router, types

from durak.logic import actions
from durak.logic.game_manager import GameManager
from durak.objects.card import Card
from durak.objects import GameNotFoundError

router = Router()


# Этот хендлер ловит все текстовые сообщения, которые генерирует инлайн-режим
@router.message(
    F.text.startswith(("⚔️", "🛡️", "🎴", "✅"))
)
async def process_text_action_handler(message: types.Message, gm: GameManager):
    """
    ОБРАБОТЧИК ИГРОВЫХ ДЕЙСТВИЙ.
    
    Перехватывает текстовые сообщения, сгенерированные инлайн-режимом
    ("Пас", "Взять", "Атака", "Защита"), и вызывает соответствующую игровую логику.
    
    GAME ACTION HANDLER.
    
    Intercepts text messages generated by the inline mode ("Pass", "Draw",
    "Attack", "Defend") and calls the corresponding game logic.
    """
    user = message.from_user
    text = message.text

    try:
        game = await gm.get_game_by_user_id(user.id)
        if not game or not game.started:
            return
        
        player = game.player_for_id(user.id)
        if not player:
            return

        # Определяем действие по тексту сообщения
        # ИСПРАВЛЕНО: Удалены некорректные проверки `player in game.attackers`, 
        # так как они вызывали ошибку AttributeError.
        # Проверка на легальность хода инкапсулирована в `actions.do_*`.
        if text == '✅ Пас':
            await actions.do_pass(game, player, gm, message.bot)
        
        elif text.startswith("🎴"): # "🎴 {mention} взял(а) карты!"
            await actions.do_draw(game, player, gm, message.bot)

        elif text.startswith("⚔️"): # "⚔️ Подкинуто карту: <card>"
            card_str = text.split(": ", 1)[1]
            atk_card = Card.from_str(card_str)
            if atk_card:
                await actions.do_attack_card(game, player, atk_card, gm, message.bot)

        elif text.startswith("🛡️"): # "🛡️ Побито карту <card> картой <card>"
            # ИСПРАВЛЕНО: Заменен вызов несуществующего метода get_first_undefended()
            # на работающую конструкцию с генератором.
            undefended_card = next((c for c, d in game.field.items() if d is None), None)
            if not undefended_card:
                return # Нечего бить

            # Извлекаем карту защиты из сообщения
            def_card_str = text.split(" ")[-1]
            def_card = Card.from_str(def_card_str)
            
            if def_card:
                 # Используем каноническую карту для атаки из состояния игры
                 await actions.do_defence_card(game, player, undefended_card, def_card, gm, message.bot)

    except (GameNotFoundError, IndexError, ValueError):
        # Игнорируем ошибки парсинга, устаревшие сообщения или если игра не найдена
        pass
    finally:
        # Удаляем сервисное сообщение, чтобы не засорять чат
        await message.delete()
